version: '3.8'

services: 
  client:
    image: nginx
    container_name: client
    ports:
      - 9100:80
    volumes: 
      - ./dist:/usr/share/nginx/html/dist
      - ./index.html:/usr/share/nginx/html/index.html